# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Enrico Pitocco"
title_separator          : "-"
name                     : &name "Enrico Pitocco"
description              : &description "Enrico Pitocco's academic portfolio"
url                      : https://enricopitocco.github.io
baseurl                  : ""
repository               : "enricopitocco/enricopitocco.github.io"

author:
  avatar           : "profile.png"
  name             : "Phd student | Brain, Mind and Computer Science"
  pronouns         :
  bio              : "Phd student in Brain, Mind and Computer Science at Università degli studi di Padova."
  location         : "Padova, Italy"
  employer         : "Università degli studi di Padova"
  uri              :
  email            : "enrico.pitocco@phd.unipd.it"
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0009-0003-3073-4013"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=59679537300"
  zotero           :
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "enricopitocco"
  kaggle           :
  stackoverflow    :
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
# The rest of the configuration stays unchanged
